version: '3.7'
services:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lancamento-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db:database"
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: on-failure

networks:
  despesas:
    driver: custom-driver-1